### ISSUE TITLE
Verifying entity in unit tests doesn't work

### ISSUE THREAD

**Issue by doggy-dev** [valid4j/http-matchers#1]
I'm trying to test an endpoint in an unittest but I'm getting the following exception when using the hasEntity() matcher:
java.lang.IllegalStateException: Method not supported on an outbound message.
	at org.glassfish.jersey.message.internal.OutboundJaxrsResponse.readEntity(OutboundJaxrsResponse.java:145)
	at org.valid4j.matchers.http.HasEntityWithValueMatcher.matchesSafely(HasEntityWithValueMatcher.java:28)
	at org.valid4j.matchers.http.HasEntityWithValueMatcher.matchesSafely(HasEntityWithValueMatcher.java:9)
	at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:55)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at my.project.endpoint.internal.v1_0.TestEndpoint_v1_0.getDeviceTypeNames(TestEndpoint_v1_0.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by helsing** [comment]
What is your use case? It seems you are trying the assertion on an OutboundJaxrsResponse, which is the server side implementation. You can't read an entity on those, since it's not supported. You will need to run your service in an actual web server (e.g tomcat, jetty), then make an actual client-side invocation of your web service and Jersey will instantiate an InboundJaxrsResponse (on the client side). Then the entity can be read, and your assertion can verify the content.

If you are tempted to short-cut the actual web server execution, remember there is lot's of "magic" going on there. Object mapping, content encoding, filters, etc, so I would recommend to actually cover all of that code via executing your service in a container (embedded web server), e.g using Dropwizard you can use a regular @ClassRule DropwizardAppRule to run your service. If you are more familiar with Spring you could try the @SpringBootTest annotations.

**Comment by doggy-dev** [comment]
I'm writing unit tests for my endpoints. I'm trying to check the entity in the Response the endpoint method returns. Until now I had to write my own matchers for the Entity inside the Response. Currently I don't have the code at my disposal but can give you an example on Monday if you're interested.

**Comment by helsing** [comment]
Closing, due to the issue described is not the expected usage of this library.
